### ISSUE TITLE
It doesn t work?

### ISSUE THREAD

**Issue by Andrejki** [8C/skypehunt#4]
Hey!
Thanks for sharing this very much. 

I did everything according to the instructions, reloaded the webpage of my skype and copied the key to the token.txt. 
However, it only shows what can be found regularly on the Skype search. 
It shows in my case for 3 accounts of the same name - skype ID, display name, profile avatar link and approximately the date when it was created. 
So it s kind of... weird, because I don t get any other results.
I ve tried another account and I ve got only: city, state, country, date of birth, gender, and the date when it was created. 

I want to get an email address or phone, preferably both. 

Best regards

**Comment by 8C** [comment]
Hello,

For certain Skype users (depending on when the account was created), the username of the skype account is the same as the email's username. As a result, for those type of accounts, the program checks the username against common email provider's domains and sees if any of them are linked to the same Skype account.

If the Skype email is not showing up, it means the account's creation date was too recent for this, or it checked the username across many common email providers but could not match the email to the Skype account in question.

Additionally, date of birth information is not available through Skype's web UI.

Regards,
8C
